### ISSUE TITLE
RM Pro Plus

### ISSUE THREAD

**Issue by alexmuntean** [uudruid74/broadlink-http-rest#3]
Hi,

This can be easily adapted to RM Pro Plus because it's like the mini version...
The think is that I can't learn RF commands...
I see that others did this but not on REST as you did. this works great. can you add support to rm pro plus also?

Thanks,
Alex

**Comment by uudruid74** [comment]
Sorry I somehow missed this.  Why can't you learn commands?  I'm confused.  This should support all RM devices as far as I know.   Does the autodetect detect your device?  Can you post the settings.ini file generated when it autodetects?  (just delete or rename settings.ini and it will generate one for you using autodetection).

**Comment by uudruid74** [comment]
This project uses mjg59's python-broadlink library.  Pull Request #156 fixes the issue you have described, and my repo should be fully compatible with the more recent versions of this library.   Upgrade your python-broadlink library to the latest version and everything should work.

See also:  https://github.com/mjg59/python-broadlink/pull/156
